print("A pleasant day!")
name=str(input("Input name:"))
age=int(input("Input age:"))
address=str(input("Input address:"))
print("Hi, my name is " + str(name) + ". I am " + str(age) + " years old and I live in " + str(address) + ".")
print("Good bye. Until we meet again " + str(name) + "!")